### PR TITLE
Added basic installation chapter

### PR DESCRIPTION
**Pull request by Nickiel12**
Added a basic installation guide with a short list of the available features, and stubbed future chapter to help users decide if they need something other than crossterm

### CODE REVIEW

**Comment by lthoerner** [comment]
https://github.com/tui-rs-revival/ratatui-book/pull/6/commits/88107a0898b5557ed5ce425036edce98dbc67df2 contains some info about Crossterm and other backends.

**Comment by Nickiel12** [comment]
@Eyesonjune18 Are you ok if I copy the section from your PR for choosing a backend?

Also, I was looking at the source for the [actual rust book](https://doc.rust-lang.org/stable/book/title-page.html), and I went with their ch##-##-XXXX.md naming structure. Do you think we should follow the scaffold Joshka set up with full names, and use folders for chapters, or the other way?

**Comment by joshka** [comment]
The only hassle with numbering from the outset is that renumbering is annoying (and breaks links people have to docs). I'd find it easier to go from no numbers to numbers if we want it later. There's been a bunch of cases over the years where documentation links have broken between versions purely due to inserting chapters, and it's pretty annoying to find the right docs later.

**Comment by Nickiel12** [comment]
That's actually a really good reason! I will go ahead and restructure this commit to use the folder structure instead of chapter names

**Comment by Nickiel12** [comment]
I have changed the file structure, and I tried to squash the commits (but I think I made it harder to understand). But as long as @Eyesonjune18 is fine with me using the portion that he linked, I think this is ready.

**Comment by lthoerner** [comment]
> @Eyesonjune18 Are you ok if I copy the section from your PR for choosing a backend?

Is there any way I could be credited on the commit? I'm not sure if that's possible (I'm relatively new to GitHub)

**Comment by Nickiel12** [comment]
> Is there any way I could be credited on the commit? I'm not sure if that's possible (I'm relatively new to GitHub)

I actually forgot to commit your instructions, so if you wanted to make a PR in the choosing-a-backend.md file, we could simply do that?

**Comment by lthoerner** [comment]
> I actually forgot to commit your instructions, so if you wanted to make a PR in the choosing-a-backend.md file, we could simply do that?

Sounds good.

**Review by joshka — APPROVED** [review]

**Pull request merged**
