### PR TITLE
Use git lfs for image storage'

### PR DESCRIPTION
**Pull request by joshka**
- move json VHS tape file under code to remove astro warning
- remove i18n content collection
- Use git lfs for image storage

### CODE REVIEW

**Comment by joshka** [comment]
Works fine on Cloudflare

**Comment by orhun** [comment]
Hey, what is the benefit of using `git-lfs` for the images?

**Comment by joshka** [comment]
If you don't, then repo bloat happens. Every time you regenerate the images a new file is added, over time this builds up and you have a huge repo and no way to make it smaller. Then you have to do shallow clones etc.

We use VHS to autogenerate image files a bunch, which tends to create new files even when nothing has changed as the gif is always slightly different. Moving to Git-LFS stores just a pointer to the file on Github as a text file. The recent Color Eyre PR has 2.7MB of images.

**Comment by kdheepak** [comment]
I've never used git-lfs. Do I just normally commit image files and with the post commit hook things are set up to work automatically?

**Comment by joshka** [comment]
yep. The hooks will warn you if git lfs isn't installed, but pretty much there's nothing to do other than just use git normally - I've added png and gif to be tracked, and there may be other files we add over time, but those seem logical to be the main ones.

**Comment by orhun** [comment]
I'm getting this now:

image

Do you know what am I supposed to do? :o

**Comment by joshka** [comment]
try `git lfs checkout`

**Comment by orhun** [comment]
```sh
Cannot checkout LFS objects, Git LFS is not installed.
```
So first I ran `git lfs install` and it worked. I think we should note this in the docs, what do you think?

**Comment by orhun** [comment]
Well actually no, I ran `git lfs install` + `git lfs fetch` but it is still not working.

```
Skipped checkout for "src/assets/logo-dark.png", content not local. Use fetch to download.
Skipped checkout for "src/assets/logo-light.png", content not local. Use fetch to download.
Skipped checkout for "src/assets/logo.png", content not local. Use fetch to download.
Skipped checkout for "src/assets/ratatui.png", content not local. Use fetch to download.
Skipped checkout for "src/content/docs/how-to/develop-apps/color-eyre/demo.gif", content not local. Use fetch to download.
Skipped checkout for "src/content/docs/how-to/develop-apps/color-eyre/error-full.gif", content not local. Use fetch to download.
Skipped checkout for "src/content/docs/how-to/develop-apps/color-eyre/error-full.png", content not local. Use fetch to download.
Skipped checkout for "src/content/docs/how-to/develop-apps/color-eyre/error.gif", content not local. Use fetch to download.
Skipped checkout for "src/content/docs/how-to/develop-apps/color-eyre/error.png", content not local. Use fetch to download.
Skipped checkout for "src/content/docs/how-to/develop-apps/color-eyre/panic-full.gif", content not local. Use fetch to download.
Skipped checkout for "src/content/docs/how-to/develop-apps/color-eyre/panic-full.png", content not local. Use fetch to download.
Skipped checkout for "src/content/docs/how-to/develop-apps/color-eyre/panic.gif", content not local. Use fetch to download.
Skipped checkout for "src/content/docs/how-to/develop-apps/color-eyre/panic.png", content not local. Use fetch to download.
Skipped checkout for "src/content/docs/how-to/develop-apps/color-eyre/quit.gif", content not local. Use fetch to download.
Skipped checkout for "src/content/docs/how-to/develop-apps/color-eyre/quit.png", content not local. Use fetch to download.
```

**Comment by orhun** [comment]
@kdheepak is it working for you, can you check?

**Comment by kdheepak** [comment]
It's working for me. I also had some issue with that particular file. This is a screenshot of my terminal history after I tried to do `git pull` without installing git lfs:

image

After installing git lfs **I had a different issue with logo-dark.png**:

image

I ran `git clean -fxd` + `git checkout -- .` + `git stash pop` + `git checkout -- .` again:

image

After that I was able to do a successful `git pull`. I ran `npm install` + `npm run dev` and it works for me:

image

**Pull request merged**
