### PR TITLE
feat: Add lychee link checker

### PR DESCRIPTION
**Pull request by kdheepak**
Lychee is a fast, async link checker

https://lychee.cli.rs/

With this github action, links are checked and if there are broken links, an issue is opened on GitHub.

### CODE REVIEW

**Comment by Valentin271** [comment]
This is a good idea and lychee looks great!

However in this state I'm pretty sure this is going to create an issue for each failed run. The best would be to have a persistent tracking issue.

**Comment by orhun** [comment]
I think creating an issue for each failed run is a bit too much. It might be especially annoying when a site is temporarily down.

We can also just include the documentation with (`*.md`) and limit the concurrency (`--max-concurrency 1`) in case the GitHub links are rate limited.

**Comment by Valentin271** [comment]
>  in case the GitHub links are rate limited.

It's possible to give an API token to lychee. I'm pretty sure github runners will have something like that included in their env.

**Comment by orhun** [comment]
Yes that's true, but GitHub still rate limits in case you send concurrent requests too fast (which was the case for me for `lychee` when I was integrating it to my projects).

**Comment by kdheepak** [comment]
This isn't particularly useful at the moment because I think for this to work well it needs a tighter integration with Astro. I'll close this issue for now and we can revisit it if things change / we find a better solution.

**Comment by orhun** [comment]
Maybe it is worth bringing up the _Astro support_ to the upstream?

**Pull request closed without merging**
