### PR TITLE
chore: update mdbook, catppuccin, admonish

### PR DESCRIPTION
**Pull request by joshka**
updated themes using mdbook-admonish/catppuccin install

### CODE REVIEW

**Comment by kdheepak** [comment]
I think this needs to be updated too for CI to work:

https://github.com/ratatui-org/ratatui-book/blob/96728675f95c66cf6cbb6676b5b94f19b53443e1/.github/workflows/mdbook.yml#L35-L38

**Comment by kdheepak** [comment]
Also, we should update this for documentation purposes:

https://github.com/ratatui-org/ratatui-book/blob/96728675f95c66cf6cbb6676b5b94f19b53443e1/src/developer-guide/book.md#L14-L21

**Comment by joshka** [comment]
I overwrote https://github.com/ratatui-org/ratatui-book/pull/108/commits/3c64e1b8dc11a313cdaf3b418d53588fa9057b6b without seeing what it contained. Can you push that to a new PR perhaps?

**Comment by kdheepak** [comment]
Did you not want to use `cargo make` for this?

**Comment by joshka** [comment]
> Did you not want to use `cargo make` for this?

I didn't see it before force pushing an amended commit, so I can't comment on what was included.

Generally I'd prefer to use xtask over cargo make if given a choice though.

**Comment by kdheepak** [comment]
I'm fine with it leaving it the way it is, but if we want to use `cargo-make` like in the main repo, here's the patch:

````diff
diff --git a/Makefile.toml b/Makefile.toml
new file mode 100644
index 0000000..b19a710
--- /dev/null
+++ b/Makefile.toml
@@ -0,0 +1,49 @@
+[config]
+skip_core_tasks = true
+
+[tasks.install-mdbook]
+command = "cargo"
+args = ["install", "mdbook", "--version", "0.4.35"]
+
+[tasks.install-mdbook-admonish]
+command = "cargo"
+args = ["install", "mdbook-admonish", "--version", "1.13.0"]
+
+[tasks.install-mdbook-svgbob2]
+command = "cargo"
+args = ["install", "mdbook-svgbob2", "--version", "0.3.0"]
+
+[tasks.install-mdbook-linkcheck]
+command = "cargo"
+args = ["install", "mdbook-linkcheck", "--version", "0.7.7"]
+
+[tasks.install-mdbook-mermaid]
+command = "cargo"
+args = ["install", "mdbook-mermaid", "--version", "0.12.6"]
+
+[tasks.install-mdbook-emojicodes]
+command = "cargo"
+args = ["install", "mdbook-emojicodes", "--version", "0.2.2"]
+
+[tasks.install-mdbook-catppuccin]
+command = "cargo"
+args = ["install", "mdbook-catppuccin", "--version", "2.0.1"]
+
+[tasks.install]
+dependencies = [
+    "install-mdbook",
+    "install-mdbook-admonish",
+    "install-mdbook-svgbob2",
+    "install-mdbook-linkcheck",
+    "install-mdbook-mermaid",
+    "install-mdbook-emojicodes",
+    "install-mdbook-catppuccin"
+]
+
+[tasks.build]
+command = "mdbook"
+args = ["build"]
+
+[tasks.serve]
+command = "mdbook"
+args = ["serve", "--open"]
diff --git a/src/developer-guide/book.md b/src/developer-guide/book.md
index fa7ff99..dd47c4f 100644
--- a/src/developer-guide/book.md
+++ b/src/developer-guide/book.md
@@ -12,12 +12,14 @@ Feel free to make contributions if you'd like to improve the documentation.
 If you want to set up your local environment, you can run the following:
 
 ```bash
-cargo install mdbook --version 0.4.30
-cargo install mdbook-admonish --version 1.9.0
-cargo install mdbook-svgbob2 --version 0.3.0
-cargo install mdbook-linkcheck --version 0.7.7
-cargo install mdbook-mermaid --version 0.12.6
-cargo install mdbook-emojicodes --version 0.2.2
+cargo install cargo-make
+cargo make install
+```
+
+You can run the following to view a local copy of the documentation:
+
+```bash
+cargo make serve
 ```
 
 These plugins allow additional features.
````

**Comment by joshka** [comment]
makes sense - yeah a single command to perform the install would be nice.
We can also achieve that by using a workspace cargo.toml file though with those dependencies called out.

**Pull request merged**
