### PR TITLE
docs: Add demo gif to tutorial/json-editor 📚

### PR DESCRIPTION
**Pull request by kyu08**
Thanks for maintaining great TUI library and its documentation! It is very helpful to construct my rust TUI app!
I've come up with an idea to make the document better and will send a PR.

## Summary
Added a demo gif to tutorial/json-editor.

## Motivation
When I actually worked on this tutorial, I first cloned the code from ratatui-org/ratatui-book and moved it to the appropriate directory and ran cargo run to see what the deliverables looked like.

I think a demo gif in the documentation would increase the motivation for beginners to work on this tutorial.

### CODE REVIEW

**Review by orhun — APPROVED** [review]

**Review by kdheepak — APPROVED** [review]

**Comment by kdheepak** [comment]
Thanks for the PR! This is great idea to add a gif.

I think we should not add the gif to the repo though. Do you think you can upload the gif to a `gist` and then link it from there? Also, you can use `vhs` to generate a gif which allows for reproducibility.

If this is too much work, no worries, I can do it and push a new commit to this PR later tonight.

**Comment by kyu08** [comment]
@kdheepak 
> Thanks for the PR! This is great idea to add a gif.

Thank you for reviewing and giving kind words!

I generated gif using `ghs` and committed its recipe as `demo.tape`. (7abc1ee2d8172f46ec9bf89067a231a2d2f0f48f)
Could check please check it?

**Comment by joshka** [comment]
The best trick is to upload the GIF to this PR and direct link to that

**Comment by kdheepak** [comment]
Thanks for making the changes! 

I'm happy to merge this as is for now. I think we'll need to figure out a way to store all the gifs at some point. @joshka we can redo it for everything in the book in a separate PR.

**Comment by kyu08** [comment]
[Gentle Reminder]
If you have a moment, could you please merge this PR when you get a chance?

**Comment by kdheepak** [comment]
Thanks for the ping! It fell off my radar 😅

**Pull request merged**
