### PR TITLE
feat(showcase): showcase paragraph widget

### PR DESCRIPTION
**Pull request by bulkan**
Relates to https://github.com/ratatui-org/website/issues/249

Followed the instructions in [Widget Showcase Readme](https://github.com/ratatui-org/website/blob/main/code/widget-showcase/README.md) to add a simple example of the Paragraph widget.

### CODE REVIEW

**Comment by Valentin271** [comment]
Hey thanks for this, what about showing a little bit more. I think centering this and having something bold/underlined/colored could be nice.

**Comment by bulkan** [comment]
@Valentin271 no problem and thanks for the feedback 🎉 

~~By centering do you mean centering the `Paragraph` in the `Frame` ?~~

Edit: I've added three lines in total. I can add a few more :)  Let me know if the sample text should be more descriptive

**Comment by Valentin271** [comment]
If I can bother you to just tweak the .tape to not have so much empty space that'd be perfect.

image

**Comment by bulkan** [comment]
Done. 

Are you also happy for me to attempt to provide PR's for the other widgets that are missing a showcase?

**Comment by Valentin271** [comment]
Of course no problem!

Thank you for this!

**Pull request merged**
