### PR TITLE
feat(rendering): link to templates

### PR DESCRIPTION
**Pull request by Valentin271**
I just feel like we should link them to say "this is a downside but we provide a workaround/help"

### CODE REVIEW

**Comment by Valentin271** [comment]
Shouldn't the cloudflare preview have run here?

**Comment by joshka** [comment]
It will only run for branches in this repo, not external forks. That's something on the Cloudflare side that they have listed as a [Known issue](https://developers.cloudflare.com/pages/platform/known-issues/)

> Commits/PRs from forked repositories will not create a preview. Support for this will come in the future.

**Review by joshka — APPROVED** [review]

**Comment by Valentin271** [comment]
I'm pretty sure the branch was on this repo, I actually created it using the web editor.

**Comment by joshka** [comment]
Oh weird. It ran (see the checks tab), but didn't add a message.
https://github.com/ratatui-org/website/pull/277/checks?check_run_id=19615039630

**Comment by Valentin271** [comment]
huh yeah true. Worth keeping an eye on to see if this is just a one-of oddity or if it happens again

**Pull request merged**
