### PR TITLE
Add counter app tutorial

### PR DESCRIPTION
**Pull request by kdheepak**

### CODE REVIEW

**Review by joshka — APPROVED** [review]
Counter tutorial docs could have more detail, but I'm assuming this is a stub and that will be expanded.

**Review by orhun — APPROVED** [review]
'tis good 💯

**Comment by kdheepak** [comment]
Yes more content to follow shortly!

**Comment by joshka** [comment]
Go home cloudflare pages bot you're drunk... This was merged months ago... ???

**Pull request merged**
